# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ "master" ]

jobs:
  build:

    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
        cache: 'npm'
      env:
        PORT: ${{secrets.PORT}}
        MYSQL_USER: ${{secrets.MYSQL_USER}}
        MYSQL_PASSWORD: ${{secrets.MYSQL_PASSWORD}}
        MYSQL_PORT: ${{secrets.MYSQL_PORT}}
        DB_NAME: ${{secrets.DB_NAME}}
        ADMIN_PASSWORD: ${{secrets.ADMIN_PASSWORD}}
        CONNECTION_STRING: ${{secrets.CONNECTION_STRING}}
        CONNECTION_STRING_TEST: ${{secrets.CONNECTION_STRING_TEST}}
        MONGOOSE_ID: ${{secrets.MONGOOSE_ID}}
        MONGOOSE_PASSWORD: ${{secrets.MONGOOSE_PASSWORD}}
        SESSION_KEY: ${{secrets.SESSION_KEY}}
        ENV: ${{secrets.ENV}}
          
    - run: npm ci
    - run: npm test
